# Generated by Django 4.1 on 2022-08-22 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
