# Generated by Django 4.1 on 2022-08-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delete_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_ID',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
